export const SUPABASE_URL = "https://kbcziosidwyvlornbaxo.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiY3ppb3NpZHd5dmxvcm5iYXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxODc5MDYsImV4cCI6MjA3OTc2MzkwNn0.qVThfoGFf2q5U0pCyLNqsNIpN362zAqF80RFuu2QgBs";
export const LOGO_URL = "https://kbcziosidwyvlornbaxo.supabase.co/storage/v1/object/sign/Migrei/Logomarca%20Migrei%20Franqueadora.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9hZWM5MDJjNy1mNDI1LTQ4NTItODY5ZC1kZTJkY2I2ZDQzMDQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJNaWdyZWkvTG9nb21hcmNhIE1pZ3JlaSBGcmFucXVlYWRvcmEucG5nIiwiaWF0IjoxNzY0MTk3OTYxLCJleHAiOjQ4ODYyNjE5NjF9.VzFmc8RwTtHxsqyTDbp6UYQIw7ds4TdwQk0raYj9F5I";
export const FRANCHISE_IMAGE_URL = "https://kbcziosidwyvlornbaxo.supabase.co/storage/v1/object/sign/Migrei/mercado-livre_energia.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9hZWM5MDJjNy1mNDI1LTQ4NTItODY5ZC1kZTJkY2I2ZDQzMDQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJNaWdyZWkvbWVyY2Fkby1saXZyZV9lbmVyZ2lhLmpwZyIsImlhdCI6MTc2NDIwMDc1OSwiZXhwIjo0ODg2MjY0NzU5fQ.YsfOs3LYsrLU-SARQvZD92BBxLQcVQiJQG0WxBkMV9s";
export const COMPANY_INFO = {
  name: "MIGREI", slogan: "Franqueadora Pioneira Oficial", whatsapp: "(11) 99999-9999", email: "contato@migreimle.com.br"
};
export const ADMIN_PASSWORD = "admin_migrei_master";