import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, BarChart3, Zap, DollarSign, Building2, Briefcase, TrendingUp, Cpu, Wallet, ChevronRight, Users, Globe, GraduationCap, BookOpen, Megaphone, Scale, Headphones, CheckCircle, Award, LineChart, Clock, Target, Percent, Crown, Rocket, MapPin, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { LOGO_URL } from '../constants';
const Home: React.FC = () => {
  const marketStats = [ { icon: BarChart3, value: "R$ 300 Bi", label: "Mercado Anual", color: "yellow" }, { icon: TrendingUp, value: "70%", label: "Não Explorado", color: "orange" }, { icon: Building2, value: "500 mil+", label: "Empresas Elegíveis", color: "amber" }, { icon: Users, value: "5 milhões", label: "Consumidores Potenciais", color: "yellow" } ];
  const franchisePackages = [ { icon: GraduationCap, title: "Cursos e Certificações", description: "Formação completa em Mercado Livre de Energia com certificação reconhecida", items: ["Curso técnico MLE (40h)", "Certificação CCEE", "Curso comercial e vendas", "Atualizações contínuas"] }, { icon: BookOpen, title: "Treinamentos Práticos", description: "Capacitação hands-on para dominar todas as operações", items: ["Análise de contas de energia", "Negociação de contratos", "Uso da plataforma", "Atendimento ao cliente"] }, { icon: Megaphone, title: "Material Publicitário", description: "Kit completo de marketing para divulgação da sua unidade", items: ["Identidade visual completa", "Materiais impressos", "Templates digitais", "Campanhas prontas"] }, { icon: Scale, title: "Apoio Jurídico", description: "Suporte legal especializado para sua operação", items: ["Contratos modelo", "Consultoria jurídica", "Compliance regulatório", "Documentação CCEE"] }, { icon: Cpu, title: "Sistema Proprietário", description: "Plataforma tecnológica completa para gestão do negócio", items: ["CRM integrado", "Migrei IA (assistente)", "Gestão de contratos", "Dashboard analítico"] }, { icon: Headphones, title: "Suporte Contínuo", description: "Acompanhamento permanente para seu sucesso", items: ["Suporte técnico 24/7", "Reuniões semanais", "Mentoria comercial", "Rede de franqueados"] } ];
  const investmentDetails = [ { icon: DollarSign, title: "Investimento Inicial", value: "R$ 80k - 150k", description: "Taxa de franquia + setup + capital de giro", color: "yellow" }, { icon: LineChart, title: "Faturamento Mensal", value: "R$ 50k - 200k", description: "Baseado em performance comercial", color: "orange" }, { icon: TrendingUp, title: "Margem Líquida", value: "25% - 35%", description: "Operação com baixo custo fixo", color: "amber" }, { icon: Clock, title: "Payback", value: "18 - 24 meses", description: "Retorno do investimento inicial", color: "yellow" }, { icon: Target, title: "Break-even", value: "3 - 6 meses", description: "Ponto de equilíbrio operacional", color: "orange" }, { icon: Percent, title: "Royalties", value: "8%", description: "Sobre faturamento bruto mensal", color: "amber" } ];
  const colorClasses: Record<string, string> = { yellow: "border-yellow-500/30 text-yellow-400", orange: "border-orange-500/30 text-orange-400", amber: "border-amber-500/30 text-amber-400" };
  return (
    <div className="overflow-hidden bg-slate-950">
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0"> <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-yellow-500/15 rounded-full blur-[100px] animate-pulse" /> <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-orange-500/15 rounded-full blur-[100px]" /> <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-amber-500/5 rounded-full blur-3xl" /> </div>
        <div className="absolute inset-0 opacity-10"> <div className="absolute inset-0" style={{ backgroundImage: `linear-gradient(to right, rgb(234, 179, 8, 0.3) 1px, transparent 1px), linear-gradient(to bottom, rgb(234, 179, 8, 0.3) 1px, transparent 1px)`, backgroundSize: '50px 50px' }} /> </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid lg:grid-cols-2 gap-16 items-center">
            <motion.div initial={{ opacity: 0, x: -40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7 }} className="relative z-10">
                <div className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-yellow-500/10 to-orange-500/10 border-2 border-yellow-500/40 rounded-full mb-8 backdrop-blur-sm"> <Crown className="w-5 h-5 text-yellow-400" /> <span className="text-yellow-400 text-sm md:text-base font-bold uppercase tracking-wide">Franqueadora Oficial</span> </div>
                <h1 className="text-5xl lg:text-7xl font-display font-black mb-6 text-white leading-tight"> <span className="bg-gradient-to-r from-yellow-400 via-amber-400 to-orange-400 bg-clip-text text-transparent">MIGREI</span> <br /> <span className="text-3xl lg:text-5xl font-extrabold text-white">MLE CONSULT</span> </h1>
                <p className="text-slate-300 mb-8 text-xl lg:text-2xl leading-relaxed"> Seja dono do seu negócio no mercado que movimenta <span className="text-yellow-400 font-bold">R$ 300 bilhões/ano</span> e está apenas 30% explorado. </p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
                <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl p-4 border border-yellow-500/30 text-center"> <div className="text-3xl font-black text-yellow-400 mb-1">18-24</div> <div className="text-[10px] text-slate-400 uppercase tracking-wide font-bold">Meses ROI</div> </div>
                <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl p-4 border border-orange-500/30 text-center"> <div className="text-3xl font-black text-orange-400 mb-1">R$80k</div> <div className="text-[10px] text-slate-400 uppercase tracking-wide font-bold">Investimento</div> </div>
                <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl p-4 border border-yellow-500/30 text-center"> <div className="text-3xl font-black text-yellow-400 mb-1">70%</div> <div className="text-[10px] text-slate-400 uppercase tracking-wide font-bold">Mercado Livre</div> </div>
                <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl p-4 border border-amber-500/30 text-center"> <div className="text-3xl font-black text-amber-400 mb-1">200k+</div> <div className="text-[10px] text-slate-400 uppercase tracking-wide font-bold">Fat. Mensal</div> </div>
                </div>
                <div className="flex flex-col sm:flex-row gap-4"> <Link to="/sobre" state={{ scrollTo: 'pricing' }} className="w-full sm:w-auto"> <button className="w-full bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white font-bold text-lg px-8 py-6 rounded-xl shadow-xl shadow-emerald-500/20 flex items-center justify-center transition-all hover:scale-105"> <Rocket className="w-5 h-5 mr-2" /> Quero Ser Franqueado </button> </Link> <Link to="/franquia" className="w-full sm:w-auto"> <button className="w-full bg-gradient-to-r from-yellow-600 to-orange-600 hover:from-yellow-500 hover:to-orange-500 text-white font-semibold text-lg px-8 py-6 rounded-xl shadow-xl shadow-yellow-500/20 flex items-center justify-center transition-all hover:scale-105"> Ver Análise Completa </button> </Link> </div>
            </motion.div>
            <motion.div initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.2 }} className="relative hidden lg:flex items-center justify-center z-0">
                <motion.div animate={{ rotate: 360 }} transition={{ duration: 30, repeat: Infinity, ease: "linear" }} className="absolute inset-0 flex items-center justify-center"> <div className="w-[500px] h-[500px] border-2 border-dashed border-yellow-500/20 rounded-full" /> <div className="absolute w-[400px] h-[400px] border border-dotted border-orange-500/20 rounded-full" /> </motion.div>
                <motion.div animate={{ y: [0, -20, 0] }} transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }} className="relative z-10"> <div className="absolute inset-0 bg-gradient-to-r from-yellow-500 to-orange-500 rounded-full blur-3xl opacity-40" /> <img src={LOGO_URL} alt="MIGREI MLE CONSULT" className="relative w-96 h-96 object-contain drop-shadow-2xl" /> </motion.div>
                <motion.div animate={{ y: [0, -10, 0], x: [0, 5, 0] }} transition={{ duration: 3, repeat: Infinity, ease: "easeInOut", delay: 0.5 }} className="absolute top-20 right-0 z-20 bg-slate-900/90 backdrop-blur-sm p-4 rounded-xl border border-yellow-500/30 shadow-xl"> <div className="flex items-center gap-3"> <TrendingUp className="w-8 h-8 text-yellow-400" /> <div> <div className="text-white font-bold">Mercado em Alta</div> <div className="text-xs text-slate-400">Crescimento exponencial</div> </div> </div> </motion.div>
                <motion.div animate={{ y: [0, 10, 0], x: [0, -5, 0] }} transition={{ duration: 3.5, repeat: Infinity, ease: "easeInOut", delay: 1 }} className="absolute bottom-20 left-0 z-20 bg-slate-900/90 backdrop-blur-sm p-4 rounded-xl border border-orange-500/30 shadow-xl"> <div className="flex items-center gap-3"> <MapPin className="w-8 h-8 text-orange-400" /> <div> <div className="text-white font-bold">Todo Brasil</div> <div className="text-xs text-slate-400">Territórios disponíveis</div> </div> </div> </motion.div>
            </motion.div>
            </div>
        </div>
      </section>
      <section className="relative py-24 bg-slate-950 overflow-hidden border-y border-slate-800">
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20"></div>
        <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(circle at 50% 50%, rgba(16, 185, 129, 0.05) 0%, transparent 50%)' }}></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-16"> <span className="text-orange-500 font-bold tracking-widest uppercase text-xs mb-2 block">Executive Snapshot</span> <h2 className="text-3xl md:text-5xl font-display font-bold text-white mb-6"> Por que investir na <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-yellow-400">MIGREI</span> agora? </h2> <div className="w-24 h-1 bg-gradient-to-r from-orange-500 to-yellow-500 mx-auto rounded-full"></div> </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} whileHover={{ y: -10 }} className="relative group p-8 rounded-3xl bg-slate-900/60 backdrop-blur-xl border border-slate-800 hover:border-orange-500/50 transition-all duration-500"> <div className="absolute inset-0 bg-gradient-to-b from-orange-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-3xl"></div> <div className="w-14 h-14 bg-slate-950 rounded-2xl flex items-center justify-center mb-6 border border-slate-800 group-hover:border-orange-500/50 shadow-lg shadow-orange-500/10"> <TrendingUp className="w-7 h-7 text-orange-400" /> </div> <h3 className="text-2xl font-bold text-white mb-2">Explosão de Mercado</h3> <div className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-yellow-400 mb-4">+262%</div> <p className="text-slate-400 leading-relaxed text-sm">Crescimento real de migrações em 2024. O momento de entrada é agora, antes da saturação dos territórios.</p> </motion.div>
                <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.1 }} whileHover={{ y: -10 }} className="relative group p-8 rounded-3xl bg-slate-900/60 backdrop-blur-xl border border-slate-800 hover:border-cyan-500/50 transition-all duration-500"> <div className="absolute inset-0 bg-gradient-to-b from-cyan-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-3xl"></div> <div className="w-14 h-14 bg-slate-950 rounded-2xl flex items-center justify-center mb-6 border border-slate-800 group-hover:border-cyan-500/50 shadow-lg shadow-cyan-500/10"> <Cpu className="w-7 h-7 text-cyan-400" /> </div> <h3 className="text-2xl font-bold text-white mb-2">Tecnologia SaaS</h3> <div className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-emerald-400 mb-4">100%</div> <p className="text-slate-400 leading-relaxed text-sm">Gestão digital. Plataforma completa com Telemetria, IA e CRM integrada para você escalar sem custos fixos altos.</p> </motion.div>
                <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.2 }} whileHover={{ y: -10 }} className="relative group p-8 rounded-3xl bg-slate-900/60 backdrop-blur-xl border border-slate-800 hover:border-emerald-500/50 transition-all duration-500"> <div className="absolute inset-0 bg-gradient-to-b from-emerald-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-3xl"></div> <div className="w-14 h-14 bg-slate-950 rounded-2xl flex items-center justify-center mb-6 border border-slate-800 group-hover:border-emerald-500/50 shadow-lg shadow-emerald-500/10"> <Wallet className="w-7 h-7 text-emerald-400" /> </div> <h3 className="text-2xl font-bold text-white mb-2">Retorno (ROI)</h3> <div className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-green-400 mb-4">150%</div> <p className="text-slate-400 leading-relaxed text-sm">Projeção de retorno sobre o capital investido já no primeiro ano de operação da unidade franqueada.</p> </motion.div>
            </div>
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mt-16 text-center">
                <Link to="/franquia" className="inline-flex items-center group relative"> <div className="absolute inset-0 bg-gradient-to-r from-orange-500 to-yellow-500 rounded-lg blur opacity-40 group-hover:opacity-75 transition-opacity animate-pulse"></div> <button className="relative px-8 py-4 bg-slate-950 border border-orange-500/50 rounded-lg text-white font-bold text-lg flex items-center gap-3 transition-transform group-hover:scale-[1.02]"> <Briefcase className="w-5 h-5 text-orange-400" /> Acessar Dossiê Completo <ChevronRight className="w-5 h-5 text-slate-500 group-hover:text-white transition-colors" /> </button> </Link>
                <div className="mt-8 flex items-center justify-center"> <div className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-500/10 border border-emerald-500/20 rounded-full backdrop-blur-md shadow-[0_0_15px_rgba(16,185,129,0.1)]"> <CheckCircle2 className="w-5 h-5 text-emerald-500" /> <span className="text-slate-300 text-sm font-medium"> Análise <span className="text-emerald-400 font-bold">Técnica</span>, <span className="text-emerald-400 font-bold">Jurídica</span> e <span className="text-emerald-400 font-bold">Comercial</span> Disponível </span> </div> </div>
            </motion.div>
        </div>
      </section>
      <section className="py-24 bg-gradient-to-b from-slate-950 to-slate-900 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-start">
            <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}> <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-500/10 border border-orange-500/30 rounded-full mb-6"> <Zap className="w-4 h-4 text-orange-400" /> <span className="text-orange-400 font-semibold uppercase tracking-wide text-xs">Oportunidade Única</span> </div> <h2 className="text-4xl lg:text-5xl font-display font-extrabold text-white mb-6 leading-tight"> O Mercado Livre de Energia é o <span className="bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent">Maior Mercado Inexplorado</span> do Brasil </h2> <p className="text-lg text-slate-400 mb-8 leading-relaxed"> Com a abertura gradual do mercado de energia elétrica, milhões de empresas e consumidores poderão escolher de quem comprar energia. Este é o momento ideal para se posicionar como especialista neste setor. </p> <div className="space-y-4"> <div className="flex items-start gap-4 bg-slate-900/50 p-4 rounded-xl border border-yellow-500/20"> <div className="bg-yellow-500/20 p-2 rounded-lg"> <Globe className="w-5 h-5 text-yellow-400" /> </div> <div> <h4 className="font-bold text-white">Regulamentação Favorável</h4> <p className="text-sm text-slate-400">Governo incentivando a migração para o Mercado Livre (Portaria 50/2022).</p> </div> </div> <div className="flex items-start gap-4 bg-slate-900/50 p-4 rounded-xl border border-orange-500/20"> <div className="bg-orange-500/20 p-2 rounded-lg"> <TrendingUp className="w-5 h-5 text-orange-400" /> </div> <div> <h4 className="font-bold text-white">Crescimento Exponencial</h4> <p className="text-sm text-slate-400">Setor cresce mais de 20% ao ano consistentemente desde 2019.</p> </div> </div> </div> </motion.div>
            <div className="flex flex-col gap-8">
              <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="grid grid-cols-2 gap-6"> {marketStats.map((stat, index) => ( <motion.div key={index} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.1 }} className={`bg-slate-900/80 backdrop-blur-sm p-6 rounded-2xl border ${ stat.color === 'yellow' ? 'border-yellow-500/30' : stat.color === 'orange' ? 'border-orange-500/30' : 'border-amber-500/30' } hover:bg-slate-800 transition-colors`}> <stat.icon className={`w-10 h-10 mb-4 ${ stat.color === 'yellow' ? 'text-yellow-400' : stat.color === 'orange' ? 'text-orange-400' : 'text-amber-400' }`} /> <div className={`text-2xl md:text-3xl font-black mb-1 ${ stat.color === 'yellow' ? 'text-yellow-400' : stat.color === 'orange' ? 'text-orange-400' : 'text-amber-400' }`}>{stat.value}</div> <div className="text-sm text-slate-400 font-bold uppercase tracking-wide">{stat.label}</div> </motion.div> ))} </motion.div>
              <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.4 }}> <Link to="/sobre" state={{ scrollTo: 'pricing' }} className="w-full inline-flex items-center justify-center px-10 py-4 bg-gradient-to-r from-orange-500 to-yellow-500 hover:from-orange-400 hover:to-yellow-400 text-slate-950 rounded-xl font-bold text-lg shadow-[0_0_20px_rgba(234,179,8,0.3)] transition-all hover:scale-[1.05] gap-2"> <Briefcase className="w-5 h-5" /> Seja um Franqueado </Link> </motion.div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-24 bg-slate-900 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16"> <div className="inline-flex items-center gap-2 px-6 py-2 bg-yellow-500/10 border-2 border-yellow-500/30 rounded-full mb-6"> <Award className="w-5 h-5 text-yellow-400" /> <span className="text-yellow-400 font-bold uppercase tracking-wide">Pacote Completo do Franqueado</span> </div> <h2 className="text-4xl lg:text-5xl font-extrabold text-white mb-4"> Tudo que Você <span className="bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent">Precisa para o Sucesso</span> </h2> <p className="text-xl text-slate-400 max-w-3xl mx-auto"> Oferecemos estrutura completa para você operar com excelência no Mercado Livre de Energia </p> </motion.div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"> {franchisePackages.map((pkg, index) => ( <motion.div key={index} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.1 }} className="bg-gradient-to-br from-slate-800/80 to-slate-900/80 backdrop-blur-sm p-8 rounded-2xl border border-yellow-500/20 hover:border-yellow-500/40 transition-all group hover:bg-slate-800"> <div className="bg-gradient-to-r from-yellow-600 to-orange-600 w-14 h-14 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform shadow-lg shadow-orange-500/20"> <pkg.icon className="w-7 h-7 text-white" /> </div> <h3 className="text-xl font-bold text-white mb-3">{pkg.title}</h3> <p className="text-slate-400 mb-5 text-sm leading-relaxed">{pkg.description}</p> <ul className="space-y-2"> {pkg.items.map((item, i) => ( <li key={i} className="flex items-center gap-2 text-sm text-slate-300"> <CheckCircle className="w-4 h-4 text-yellow-500 flex-shrink-0" /> {item} </li> ))} </ul> </motion.div> ))} </div>
        </div>
      </section>
      <section className="py-24 bg-slate-950 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16"> <h2 className="text-4xl lg:text-5xl font-extrabold text-white mb-4"> <span className="bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent">Números</span> do Investimento </h2> <p className="text-xl text-slate-400 max-w-3xl mx-auto"> Transparência total sobre o modelo financeiro da franquia MIGREI MLE CONSULT </p> </motion.div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"> {investmentDetails.map((item, index) => ( <motion.div key={index} initial={{ opacity: 0, scale: 0.95 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: index * 0.1 }} className={`bg-slate-900/60 backdrop-blur-sm p-8 rounded-2xl border-2 ${colorClasses[item.color].split(' ')[0]} hover:bg-slate-900/80 transition-all`}> <item.icon className={`w-12 h-12 ${colorClasses[item.color].split(' ')[1]} mb-4`} /> <h3 className="text-lg font-semibold text-slate-300 mb-2">{item.title}</h3> <p className={`text-4xl font-black ${colorClasses[item.color].split(' ')[1]} mb-2`}>{item.value}</p> <p className="text-sm text-slate-500">{item.description}</p> </motion.div> ))} </div>
          <motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="mt-12 text-center text-sm text-slate-500 max-w-2xl mx-auto"> * Os valores apresentados são estimativas baseadas em unidades em operação. Resultados podem variar de acordo com região, dedicação e condições de mercado. </motion.p>
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.2 }} className="mt-12 text-center"> <Link to="/sobre" state={{ scrollTo: 'pricing' }} className="inline-flex items-center justify-center px-10 py-4 bg-gradient-to-r from-orange-500 to-yellow-500 hover:from-orange-400 hover:to-yellow-400 text-slate-950 rounded-xl font-bold text-lg shadow-[0_0_20px_rgba(234,179,8,0.3)] transition-all hover:scale-[1.05] gap-2"> <Briefcase className="w-5 h-5" /> Seja um Franqueado </Link> </motion.div>
        </div>
      </section>
    </div>
  );
};
export default Home;