import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Bot, Send, Shield, Lock, Unlock, User, Sparkles, AlertTriangle, X, FileText, Zap } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { sendMessageToGemini } from '../services/geminiService';
import { AccessLevel } from '../types';
interface Message { id: string; role: 'user' | 'model'; text: string; timestamp: Date; }
const MigreiIA: React.FC = () => {
  const { user, profile } = useAuth();
  const [messages, setMessages] = useState<Message[]>([ { id: 'welcome', role: 'model', text: `Olá! Eu sou a Migrei IA. 🤖\n\nSou especialista em Mercado Livre de Energia. Posso te ajudar a entender sua fatura, explicar regulações ou analisar seu consumo.\n\nPor padrão, **não tenho acesso** aos seus dados financeiros para sua segurança.`, timestamp: new Date() } ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isFinancialAccessGranted, setIsFinancialAccessGranted] = useState(false);
  const [showPermissionModal, setShowPermissionModal] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const scrollToBottom = () => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); };
  useEffect(() => { scrollToBottom(); }, [messages]);
  const handleSend = async () => {
    if (!input.trim() || isLoading) return;
    const userMessage: Message = { id: Date.now().toString(), role: 'user', text: input, timestamp: new Date() };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);
    const history = messages.map(m => ({ role: m.role, text: m.text }));
    const responseText = await sendMessageToGemini( userMessage.text, history, profile?.role === 'client' ? AccessLevel.CLIENT : AccessLevel.BASIC, user?.id, isFinancialAccessGranted );
    const botMessage: Message = { id: (Date.now() + 1).toString(), role: 'model', text: responseText, timestamp: new Date() };
    setMessages(prev => [...prev, botMessage]);
    setIsLoading(false);
  };
  const toggleFinancialAccess = () => { if (!isFinancialAccessGranted) { setShowPermissionModal(true); } else { setIsFinancialAccessGranted(false); setMessages(prev => [...prev, { id: Date.now().toString(), role: 'model', text: "🔒 **Modo Privacidade Ativado.** Desconectei o acesso aos seus dados financeiros. Minhas próximas respostas serão baseadas apenas em conhecimento geral de mercado.", timestamp: new Date() }]); } };
  const confirmAccess = () => { setIsFinancialAccessGranted(true); setShowPermissionModal(false); setMessages(prev => [...prev, { id: Date.now().toString(), role: 'model', text: "🔓 **Modo Consultor Financeiro Ativado.** Agora consigo analisar suas faturas e consumo para te dar respostas personalizadas. \n\n*Nota: Seus dados são lidos apenas no momento da pergunta e não são armazenados para treinamento.*", timestamp: new Date() }]); };
  return (
    <div className="min-h-screen bg-slate-950 flex flex-col pt-20 relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-full pointer-events-none"> <div className="absolute top-20 right-0 w-[500px] h-[500px] bg-indigo-500/10 rounded-full blur-[100px]" /> <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-[100px]" /> </div>
      <div className="max-w-5xl mx-auto w-full flex-1 flex flex-col p-4 relative z-10">
        <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800 rounded-2xl p-4 mb-4 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-xl"> <div className="flex items-center gap-3"> <div className="w-12 h-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-500/20"> <Bot className="w-7 h-7 text-white" /> </div> <div> <h1 className="text-xl font-bold text-white flex items-center gap-2"> Migrei IA <span className="text-[10px] bg-indigo-500/20 text-indigo-300 px-2 py-0.5 rounded-full border border-indigo-500/30">BETA</span> </h1> <p className="text-xs text-slate-400">Inteligência Artificial Generativa (Gemini 2.5)</p> </div> </div> <div className="flex items-center gap-3 bg-slate-950 p-2 rounded-xl border border-slate-800"> <div className="text-right hidden sm:block"> <p className={`text-xs font-bold ${isFinancialAccessGranted ? 'text-emerald-400' : 'text-slate-400'}`}> {isFinancialAccessGranted ? 'Dados Conectados' : 'Modo Privado'} </p> <p className="text-[10px] text-slate-500"> {isFinancialAccessGranted ? 'Consultor Financeiro Ativo' : 'Acesso a faturas bloqueado'} </p> </div> <button onClick={toggleFinancialAccess} className={`relative w-14 h-8 rounded-full transition-colors duration-300 flex items-center ${isFinancialAccessGranted ? 'bg-emerald-500' : 'bg-slate-700'}`}> <div className={`absolute w-6 h-6 bg-white rounded-full shadow-md transform transition-transform duration-300 flex items-center justify-center ${isFinancialAccessGranted ? 'translate-x-7' : 'translate-x-1'}`}> {isFinancialAccessGranted ? <Unlock className="w-3 h-3 text-emerald-600" /> : <Lock className="w-3 h-3 text-slate-500" />} </div> </button> </div> </div>
        <div className="flex-1 bg-slate-900/50 border border-slate-800 rounded-2xl p-4 mb-4 overflow-y-auto custom-scrollbar relative"> {messages.length === 0 && ( <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-500 opacity-50 pointer-events-none"> <Bot className="w-16 h-16 mb-4" /> <p>Inicie uma conversa...</p> </div> )} <div className="space-y-6"> {messages.map((msg) => ( <motion.div key={msg.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}> <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${msg.role === 'user' ? 'bg-slate-800 border border-slate-700' : 'bg-indigo-600 shadow-lg shadow-indigo-600/20'}`}> {msg.role === 'user' ? <User className="w-5 h-5 text-slate-300" /> : <Sparkles className="w-5 h-5 text-white" />} </div> <div className={`max-w-[80%] p-4 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap shadow-md ${msg.role === 'user' ? 'bg-slate-800 text-slate-200 rounded-tr-none' : 'bg-slate-950 border border-slate-800 text-slate-300 rounded-tl-none'}`}> {msg.role === 'model' && ( <span className="block text-[10px] font-bold text-indigo-400 mb-1 uppercase tracking-wider">Migrei IA</span> )} {msg.text} </div> </motion.div> ))} {isLoading && ( <div className="flex gap-4"> <div className="w-10 h-10 bg-indigo-600 rounded-full flex items-center justify-center shrink-0 shadow-lg shadow-indigo-600/20"> <Bot className="w-5 h-5 text-white animate-pulse" /> </div> <div className="bg-slate-950 border border-slate-800 p-4 rounded-2xl rounded-tl-none flex items-center gap-2"> <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div> <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div> <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div> </div> </div> )} <div ref={messagesEndRef} /> </div> </div>
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-2 flex items-center gap-2 shadow-xl relative z-20"> <input type="text" value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleSend()} placeholder={isFinancialAccessGranted ? "Pergunte sobre sua conta, economia ou mercado..." : "Pergunte sobre o Mercado Livre de Energia..."} className="flex-1 bg-transparent border-none focus:ring-0 text-white placeholder-slate-500 px-4 py-3" disabled={isLoading} /> <button onClick={handleSend} disabled={!input.trim() || isLoading} className="p-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-indigo-500/20"> <Send className="w-5 h-5" /> </button> </div>
      </div>
      <AnimatePresence> {showPermissionModal && ( <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm"> <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }} className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-lg shadow-2xl p-6 relative"> <button onClick={() => setShowPermissionModal(false)} className="absolute top-4 right-4 text-slate-400 hover:text-white"> <X className="w-5 h-5" /> </button> <div className="flex items-center gap-4 mb-6"> <div className="p-3 bg-emerald-500/10 rounded-full border border-emerald-500/20"> <Shield className="w-8 h-8 text-emerald-500" /> </div> <h2 className="text-xl font-bold text-white">Autorizar Acesso a Dados?</h2> </div> <div className="space-y-4 mb-8"> <p className="text-slate-300 leading-relaxed"> Para responder perguntas sobre sua conta, a Migrei IA precisa de permissão para ler temporariamente: </p> <ul className="space-y-2"> <li className="flex items-center gap-3 text-sm text-slate-400"> <FileText className="w-4 h-4 text-indigo-400" /> Histórico de Faturas e Valores </li> <li className="flex items-center gap-3 text-sm text-slate-400"> <Zap className="w-4 h-4 text-indigo-400" /> Padrões de Consumo e Telemetria </li> </ul> <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex gap-3"> <AlertTriangle className="w-5 h-5 text-orange-500 shrink-0" /> <p className="text-xs text-slate-400"> <strong className="text-orange-400 block mb-1">Compromisso de Privacidade:</strong> Seus dados financeiros serão injetados no contexto da IA <strong>apenas para esta sessão</strong> e não serão armazenados ou usados para treinar o modelo global. </p> </div> </div> <div className="flex gap-3"> <button onClick={() => setShowPermissionModal(false)} className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 text-white font-bold rounded-xl transition-colors"> Cancelar </button> <button onClick={confirmAccess} className="flex-1 py-3 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl transition-colors shadow-lg shadow-emerald-500/20"> Autorizar Acesso Seguro </button> </div> </motion.div> </div> )} </AnimatePresence>
    </div>
  );
};
export default MigreiIA;